### ISSUE TITLE
ImmVibeSPI: Set a vibrator value. (From RedMi 1S)

### ISSUE THREAD

**Issue by danielstuart14** [dh-harald/android_kernel_xiaomi_ferrari#1]
I think we can solve the vibration issue. I was taking a look on armani (red 1s) source, and I figure out the vibe hardware are essential the same from Mi 2i. Looking deeper, I saw that the intensity code is different, on armani we've a code that sets the intensity using pwm period multiplied by level. So, we can't just port armani's vibration commit. 

Here, we are able to do two things: We can just port the commit to our device, and still using our vibe driver. Or, we can port the entirely ImmVibeSPI driver from armani,  fixing any issue that it could has on 3.10 kernel. (Armani is 3.4)

Here is the commit: https://github.com/armani-dev/android_kernel_xiaomi_armani/commit/21e84436fde3ccbb829082e1ab6b3c733df6e237

I'm working on it, but as I can't test (I don't have the device), i think it's better to someone how has do it.

**Comment by dh-harald** [comment]
Hi,

I've implemented your patch idea (it can't be compiled) it's not working... 
It's something quietly different...
